interfaces:
  - name: e0/0
    description: mgt_interface
    enabled: true
  - name: e0/1
    description: to_CSW1
    enabled: true
  - name: e0/2
    description: to_CSW2
    enabled: true
  - name: e0/3
    description: access interface
    enabled: true
  - name: e1/0
    description: access interface
    enabled: true


interfaces_l2:
  - name: e0/0
    mode: access
    access:
      vlan: 1
  - name: e0/1
    mode: trunk
    trunk:
      allowed_vlans:
        - 10
        - 20
        - 99
      native_vlan: 99
      encapsulation: dot1q
  - name: e0/1
    mode: trunk
    trunk:
      allowed_vlans:
        - 10
        - 20
        - 99
      native_vlan: 99
      encapsulation: dot1q
  - name: e0/3
    mode: access
    access:
      vlan: 10
  - name: e1/0
    mode: access
    access:
      vlan: 20