interfaces:
  - name: e0/0
    description: mgt_interface
    enabled: true
  - name: e0/1
    description: to_R1
    enabled: true
  - name: e0/2
    description: to_R2
    enabled: true
  - name: e0/3
    description: to_ASW1
    enabled: true
  - name: e1/0
    description: to_ASW2
    enabled: true
  - name: e1/1
    description: ether channel to CSW2
    enabled: true
  - name: e1/2
    description: ether channel to CSW2
    enabled: true
  - name: e1/3
    description: ether channel to CSW2
    enabled: true
  - name: vlan 10
    description: LAN1
    enabled: true
  - name: vlan 20
    description: LAN2
    enabled: true


interfaces_l2:
#  - name: e0/0
#    mode: access
#    access:
#      vlan: 1
  - name: e0/3
    mode: trunk
    trunk:
      allowed_vlans:
        - 10
        - 20
        - 99
      native_vlan: 1
      encapsulation: dot1q
  - name: e1/0
    mode: trunk
    trunk:
      allowed_vlans:
        - 10
        - 20
        - 99
      native_vlan: 1
      encapsulation: dot1q

interfaces_l3:
  - name: vlan 10
    ipv4:
      - address: 192.168.2.1/24
  - name: vlan 20
    ipv4:
      - address: 192.168.3.1/24
  - name: e0/1
    ipv4:
      - address: 192.168.0.1/30
  - name: e0/2
    ipv4:
      - address: 192.168.0.5/30

helper_addresses:
  - interface: vlan 10
    helper_address: 192.168.5.10

  - interface: vlan 20
    helper_address: 192.168.5.10

ospf:
  processes:
    - process_id: 1
      router_id: 1.1.1.1
      network:
        - address: 192.168.2.0
          wildcard_bits: 0.0.0.255
          area: 0
        - address: 192.168.3.0
          wildcard_bits: 0.0.0.255
          area: 0
        - address: 192.168.0.0
          wildcard_bits: 0.0.0.3
          area: 0
        - address: 192.168.0.4
          wildcard_bits: 0.0.0.3
          area: 0

vrrps:
  - id: 10
    interface: vlan 10
    virtual_ip: 192.168.2.3
    priority: 100
    preempt: true
  - id: 20
    interface: vlan 20
    virtual_ip: 192.168.3.3
    priority: 100
    preempt: true