interfaces:
  - name: e0/0
    description: mgt_interface
    enabled: true
  - name: e0/1
    description: to_R2
    enabled: true
  - name: e0/2
    description: to_R1
    enabled: true
  - name: e0/3
    description: to_ASW2
    enabled: true
  - name: e1/0
    description: to_ASW1
    enabled: true
  - name: e1/1
    description: ether channel to CSW1
    enabled: true
  - name: e1/2
    description: ether channel to CSW1
    enabled: true
  - name: e1/3
    description: ether channel to CSW1
    enabled: true
  - name: vlan 10
    description: ether channel to CSW2
    enabled: true
  - name: vlan 20
    description: ether channel to CSW2
    enabled: true

interfaces_l2:
#  - name: e0/0
#    mode: access
#    access:
#      vlan: 1
  - name: e0/3
    mode: trunk
    trunk:
      allowed_vlans:
        - 10
        - 20
        - 99
      native_vlan: 1
      encapsulation: dot1q
  - name: e1/0
    mode: trunk
    trunk:
      allowed_vlans:
        - 10
        - 20
        - 99
      native_vlan: 1
      encapsulation: dot1q


interfaces_l3:
  - name: vlan 10
    ipv4:
      - address: 192.168.2.2/24
  - name: vlan 20
    ipv4:
      - address: 192.168.3.2/24
  - name: e0/1
    ipv4:
      - address: 192.168.0.9/30
  - name: e0/2
    ipv4:
      - address: 192.168.0.13/30