interfaces:
  - name: e0/0
    description: mgt_interface
    enabled: true
  - name: e0/1
    description: to backbone switch
    enabled: true
  - name: e0/2
    description: to R3
    enabled: true
  - name: e0/3
    description: to R2
    enabled: true
  - name: e1/0
    description: to CSW1
    enabled: true
  - name: e1/1
    description: to CSW2
    enabled: true

interfaces_l3:
  - name: e0/0
    ipv4:
      - address: 192.168.1.5/24
  - name: e0/1
    ipv4:
      - address: 192.168.4.1/29
  - name: e0/2
    ipv4:
      - address: 192.168.0.17/30
  - name: e0/3
    ipv4:
      - address: 192.168.0.21/30
  - name: e1/0
    ipv4:
      - address: 192.168.0.2/30
  - name: e1/1
    ipv4:
      - address: 192.168.0.14/30



ospf:
  processes:
    - process_id: 1
      router_id: 1.1.2.1
      network:
        - address: 192.168.1.0
          wildcard_bits: 0.0.0.0
          area: 0
        - address: 192.168.4.0
          wildcard_bits: 0.0.0.7
          area: 0
        - address: 192.168.0.16
          wildcard_bits: 0.0.0.3
          area: 0
        - address: 192.168.0.20
          wildcard_bits: 0.0.0.3
          area: 0
        - address: 192.168.0.0
          wildcard_bits: 0.0.0.3
          area: 0
        - address: 192.168.0.12
          wildcard_bits: 0.0.0.3
          area: 0