interfaces:
  - name: e0/0
    description: mgt_interface
    enabled: true
  - name: e0/1
    description: to backbone switch
    enabled: true
  - name: e0/2
    description: to R4
    enabled: true
  - name: e0/3
    description: to R1
    enabled: true
  - name: e1/0
    description: to CSW2
    enabled: true
  - name: e1/1
    description: to CSW1
    enabled: true

interfaces_l3:
  - name: e0/0
    ipv4:
      - address: 192.168.1.6/24
  - name: e0/1
    ipv4:
      - address: 192.168.4.2/29
  - name: e0/2
    ipv4:
      - address: 192.168.0.25/30
  - name: e0/3
    ipv4:
      - address: 192.168.0.22/30
  - name: e1/0
    ipv4:
      - address: 192.168.0.10/30
  - name: e1/1
    ipv4:
      - address: 192.168.0.6/30