interfaces:
  - name: e0/0
    description: mgt_interface
    enabled: true
  - name: e0/1
    description: to backbone switch
    enabled: true
  - name: e0/2
    description: to R1
    enabled: true
  - name: e0/3
    description: to R4
    enabled: true
  - name: e1/0
    description: LAN3
    enabled: true


interfaces_l3:
  - name: e0/0
    ipv4:
      - address: 192.168.1.7/24
  - name: e0/1
    ipv4:
      - address: 192.168.4.3/29
  - name: e0/2
    ipv4:
      - address: 192.168.0.18/30
  - name: e0/3
    ipv4:
      - address: 192.168.0.29/30
  - name: e1/0
    ipv4:
      - address: 192.168.5.1/24

ospf:
  processes:
    - process_id: 1
      router_id: 1.1.2.1
      networks:
        - prefix: 192.168.1.0
          mask: 255.255.255.0
          area: 0
        - prefix: 192.168.4.0
          mask: 255.255.255.248
          area: 0
        - prefix: 192.168.0.16
          mask: 255.255.255.0
          area: 0
        - prefix: 192.168.0.28
          mask: 255.255.255.252
          area: 0
        - prefix: 192.168.5.0
          mask: 255.255.255.0
          area: 0
