interfaces:
  - name: e0/0
    description: mgt_interface
    enabled: true
  - name: e0/1
    description: to backbone switch
    enabled: true
  - name: e0/2
    description: to R1
    enabled: true
  - name: e0/3
    description: to R4
    enabled: true
  - name: e1/0
    description: LAN3
    enabled: true


interfaces_l3:
  - name: e0/0
    ipv4:
      - address: 192.168.1.7/24
  - name: e0/1
    ipv4:
      - address: 192.168.4.3/29
  - name: e0/2
    ipv4:
      - address: 192.168.0.18/30
  - name: e0/3
    ipv4:
      - address: 192.168.0.29/30
  - name: e1/0
    ipv4:
      - address: 192.168.5.1/24

ospf:
  processes:
    - process_id: 1
      router_id: 1.1.2.3
      network:
        - address: 192.168.1.0
          wildcard_bits: 0.0.0.255
          area: 0
        - address: 192.168.4.0
          wildcard_bits: 0.0.0.7
          area: 0
        - address: 192.168.0.16
          wildcard_bits: 0.0.0.255
          area: 0
        - address: 192.168.0.28
          wildcard_bits: 0.0.0.3
          area: 0
        - address: 192.168.5.0
          wildcard_bits: 0.0.0.255
          area: 0
      passive_interfaces:
        default: true
        interfaces:
          set_interface: false
          name:
            - e0/1
            - e0/2
            - e0/3